GET http://localhost:8080/car HTTP/1.1


###
GET http://localhost:8080/car/639426bfc02d1ec26a9caf94  HTTP/1.1

###
POST http://localhost:8080/car HTTP/1.1
Content-Type: application/json

{
    "model":"Subaru",
    "color":"Purple"
}
